# Generated by Django 5.2.1 on 2025-07-04 10:56

import apps.pictures.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pictures", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picture",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="picture",
            name="picture",
            field=models.ImageField(upload_to=apps.pictures.models.upload_to),
        ),
    ]
