# Generated by Django 5.2.1 on 2025-08-18 15:12

import django.utils.timezone
import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pictures", "0004_picture_likes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="picture",
            options={"ordering": ["-created"]},
        ),
        migrations.AddField(
            model_name="picture",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="picture",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
    ]
