# Generated by Django 5.2.1 on 2025-10-30 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pictures", "0007_comment_picture_comments"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="picture",
            name="comments",
            field=models.ManyToManyField(
                related_name="commented_pictures",
                through="pictures.Comment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="picture",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_pictures", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="picture",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploaded_pictures",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
