[program:<PROJECT_NAME>_gunicorn]
command=<PROJECT_DIRECTORY>/backend/.venv/bin/gunicorn --workers 3 --bind unix:/run/<PROJECT_NAME>.sock django_project.wsgi:application
directory=<PROJECT_DIRECTORY>/backend
user=leigh
group=www-data
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/supervisor/<PROJECT_NAME>_gunicorn.log
stderr_logfile=/var/log/supervisor/<PROJECT_NAME>_gunicorn_err.log